-- add carcass_disposed to incidents_animal
alter table "INCIDENTS_ANIMAL"
  add (
    "CARCASS_DISPOSED" NUMBER(1) CHECK (
      ("CARCASS_DISPOSED" IN (0,1)) OR ("CARCASS_DISPOSED" IS NULL)
    )
  )
;

-- add human_interaction to incidents_case
/* note that the DEFAULT clause isn't generated by Django's table def, but makes
 * sense.
 */
alter table "INCIDENTS_CASE"
  add ("HUMAN_INTERACTION" NVARCHAR2(3) DEFAULT 'unk')
;

-- add animal_length to incidents_observation
alter table "INCIDENTS_OBSERVATION"
  add ("ANIMAL_LENGTH" NUMBER(6, 4))
;

-- add animal_length_sigdigs to incidents_observation
alter table "INCIDENTS_OBSERVATION"
  add ("ANIMAL_LENGTH_SIGDIGS" NUMBER(11))
;


-- add indication_entanglement to incidents_observation
alter table "INCIDENTS_OBSERVATION"
  add (
    "INDICATION_ENTANGLEMENT" NUMBER(1) CHECK (
      (
        "INDICATION_ENTANGLEMENT" IN (0,1)
      ) OR (
        "INDICATION_ENTANGLEMENT" IS NULL
      )
    )
  )
;

-- add indication_shipstrike to incidents_observation
alter table "INCIDENTS_OBSERVATION"
  add (
    "INDICATION_SHIPSTRIKE" NUMBER(1) CHECK (
      ("INDICATION_SHIPSTRIKE" IN (0,1)) OR ("INDICATION_SHIPSTRIKE" IS NULL)
    )
  )
;

