CREATE TABLE "ENTANGLEMENTS_ENTANGLEMENT54D9" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "ENTANGLEMENT_ID" NUMBER(11) NOT NULL,
    "GEARTYPE_ID" NUMBER(11) NOT NULL REFERENCES "ENTANGLEMENTS_GEARTYPE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    UNIQUE ("ENTANGLEMENT_ID", "GEARTYPE_ID")
)
;

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(*) INTO i FROM USER_CATALOG
        WHERE TABLE_NAME = 'ENTANGLEMENTS_ENTANGLEM487A_SQ' AND TABLE_TYPE = 'SEQUENCE';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "ENTANGLEMENTS_ENTANGLEM487A_SQ"';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER "ENTANGLEMENTS_ENTANGLEM487A_TR"
BEFORE INSERT ON "ENTANGLEMENTS_ENTANGLEMENT54D9"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "ENTANGLEMENTS_ENTANGLEM487A_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/
