-- add carcass_disposed to incidents_animal
alter table "incidents_animal"
add "carcass_disposed" bool
;

-- add human_interaction to incidents_case
/* note that the DEFAULT clause isn't generated by Django's table def, but makes
 * sense.
 */
alter table "incidents_case"
add "human_interaction" varchar(3) NOT NULL DEFAULT "unk"
;

-- add animal_length to incidents_observation
alter table "incidents_observation"
add "animal_length" decimal
;

-- add animal_length_sigdigs to incidents_observation
alter table "incidents_observation"
add "animal_length_sigdigs" integer
;

-- add indication_entanglement to incidents_observation
alter table "incidents_observation"
add "indication_entanglement" bool
;

-- add indication_shipstrike to incidents_observation
alter table "incidents_observation"
add "indication_shipstrike" bool
;

