-- add the "entanglements_locationgearset" table
CREATE TABLE "ENTANGLEMENTS_LOCATIONGEARSET" (
    "LOCATION_PTR_ID" NUMBER(11) NOT NULL PRIMARY KEY REFERENCES "LOCATIONS_LOCATION" ("ID") DEFERRABLE INITIALLY DEFERRED,
    "DEPTH" NUMBER(8, 3),
    "DEPTH_SIGDIGS" NUMBER(11),
    "BOTTOM_TYPE" NVARCHAR2(1024)
)
;
-- add a LocationGearSet for every GearOwner
insert into ENTANGLEMENTS_LOCATIONGEARSET ( LOCATION_PTR_ID )
select location_gear_set_id
from ENTANGLEMENTS_GEAROWNER
where location_gear_set_id is not null
;
-- change the reference of "entanglements_gearowner.location_gear_set_id" to "entanglements_locationgearset.location_ptr_id"
/* just done in SQL Developer
 */

-- add the entanglements_gearattribute table
CREATE TABLE "ENTANGLEMENTS_GEARATTRIBUTE" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "NAME" NVARCHAR2(512)
)
;

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(*) INTO i FROM USER_CATALOG
        WHERE TABLE_NAME = 'ENTANGLEMENTS_GEARATTRIBUTE_SQ' AND TABLE_TYPE = 'SEQUENCE';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "ENTANGLEMENTS_GEARATTRIBUTE_SQ"';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER "ENTANGLEMENTS_GEARATTRIBUTE_TR"
BEFORE INSERT ON "ENTANGLEMENTS_GEARATTRIBUTE"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "ENTANGLEMENTS_GEARATTRIBUTE_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/

-- add the entanglements_entanglement_gear_attributes table
CREATE TABLE "ENTANGLEMENTS_ENTANGLEMENT4CB4" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "ENTANGLEMENT_ID" NUMBER(11) NOT NULL,
    "GEARATTRIBUTE_ID" NUMBER(11) NOT NULL REFERENCES "ENTANGLEMENTS_GEARATTRIBUTE" ("ID") DEFERRABLE INITIALLY DEFERRED,
    UNIQUE ("ENTANGLEMENT_ID", "GEARATTRIBUTE_ID")
)
;

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(*) INTO i FROM USER_CATALOG
        WHERE TABLE_NAME = 'ENTANGLEMENTS_ENTANGLEM57CC_SQ' AND TABLE_TYPE = 'SEQUENCE';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "ENTANGLEMENTS_ENTANGLEM57CC_SQ"';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER "ENTANGLEMENTS_ENTANGLEM57CC_TR"
BEFORE INSERT ON "ENTANGLEMENTS_ENTANGLEMENT4CB4"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "ENTANGLEMENTS_ENTANGLEM57CC_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/

ALTER TABLE "ENTANGLEMENTS_ENTANGLEMENT4CB4" ADD CONSTRAINT "ENTANGLEMENT_ID_REFS_CASE_D654" FOREIGN KEY ("ENTANGLEMENT_ID") REFERENCES "ENTANGLEMENTS_ENTANGLEMENT" ("CASE_PTR_ID") DEFERRABLE INITIALLY DEFERRED;

-- add the entanglements_entanglement_gear_targets table
CREATE TABLE "ENTANGLEMENTS_ENTANGLEMENT97E0" (
    "ID" NUMBER(11) NOT NULL PRIMARY KEY,
    "ENTANGLEMENT_ID" NUMBER(11) NOT NULL,
    "TAXON_ID" NUMBER(11) NOT NULL REFERENCES "TAXONS_TAXON" ("ID") DEFERRABLE INITIALLY DEFERRED,
    UNIQUE ("ENTANGLEMENT_ID", "TAXON_ID")
)
;

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(*) INTO i FROM USER_CATALOG
        WHERE TABLE_NAME = 'ENTANGLEMENTS_ENTANGLEMA119_SQ' AND TABLE_TYPE = 'SEQUENCE';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "ENTANGLEMENTS_ENTANGLEMA119_SQ"';
    END IF;
END;
/

CREATE OR REPLACE TRIGGER "ENTANGLEMENTS_ENTANGLEMA119_TR"
BEFORE INSERT ON "ENTANGLEMENTS_ENTANGLEMENT97E0"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "ENTANGLEMENTS_ENTANGLEMA119_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/

ALTER TABLE "ENTANGLEMENTS_ENTANGLEMENT97E0" ADD CONSTRAINT "ENTANGLEMENT_ID_REFS_CASE_A23B" FOREIGN KEY ("ENTANGLEMENT_ID") REFERENCES "ENTANGLEMENTS_ENTANGLEMENT" ("CASE_PTR_ID") DEFERRABLE INITIALLY DEFERRED;

-- add 4 fields to entanglements_entanglement
alter table "ENTANGLEMENTS_ENTANGLEMENT"
add "NUM_GEAR_TYPES" NUMBER(11)
;
alter table "ENTANGLEMENTS_ENTANGLEMENT"
add "GEAR_COMPLIANT" NUMBER(1) CHECK (("GEAR_COMPLIANT" IN (0,1)) OR ("GEAR_COMPLIANT" IS NULL))
;
alter table "ENTANGLEMENTS_ENTANGLEMENT"
add "GEAR_KEPT" NUMBER(1) CHECK (("GEAR_KEPT" IN (0,1)) OR ("GEAR_KEPT" IS NULL))
;
alter table "ENTANGLEMENTS_ENTANGLEMENT"
add  "GEAR_KEPT_WHERE" NCLOB
;

-- add 3 fields to "entanglements_entanglementobservation"
alter table "ENTANGLEMENTS_ENTANGLEMENT4F56"
add "GEAR_RETRIEVER_ID" NUMBER(11) REFERENCES "CONTACTS_CONTACT" ("ID") DEFERRABLE INITIALLY DEFERRED
;
CREATE INDEX "ENTANGLEMENTS_ENTANGLEMENT69D9" ON "ENTANGLEMENTS_ENTANGLEMENT4F56" ("GEAR_RETRIEVER_ID");

alter table "ENTANGLEMENTS_ENTANGLEMENT4F56"
add "GEAR_GIVEN_DATE" DATE
;
alter table "ENTANGLEMENTS_ENTANGLEMENT4F56"
add "GEAR_GIVER_ID" NUMBER(11) REFERENCES "CONTACTS_CONTACT" ("ID") DEFERRABLE INITIALLY DEFERRED
;
CREATE INDEX "ENTANGLEMENTS_ENTANGLEMENTFC43" ON "ENTANGLEMENTS_ENTANGLEMENT4F56" ("GEAR_GIVER_ID");
