-- add the three new fields
alter table ENTANGLEMENTS_ENTANGLEMENT
add "GEAR_DESCRIPTION" NCLOB
;

alter table ENTANGLEMENTS_ENTANGLEMENT
add "GEAR_ANALYSIS_COMMENTS" NCLOB
;

alter table ENTANGLEMENTS_ENTANGLEMENT
add "GEAR_ANALYSIS_CONCLUSIONS" NCLOB
;

-- copy values
update ENTANGLEMENTS_ENTANGLEMENT 
  set GEAR_DESCRIPTION = (
    select MISSING_GEAR 
    from ENTANGLEMENTS_GEAROWNER 
    where ENTANGLEMENTS_GEAROWNER.ID = ENTANGLEMENTS_ENTANGLEMENT.GEAR_OWNER_INFO_ID
  )
;

-- check that they're correct
select
  ENTANGLEMENTS_ENTANGLEMENT.GEAR_OWNER_INFO_ID,
  ENTANGLEMENTS_GEAROWNER.ID,
  ENTANGLEMENTS_ENTANGLEMENT.GEAR_DESCRIPTION,
  ENTANGLEMENTS_GEAROWNER.MISSING_GEAR
from ENTANGLEMENTS_ENTANGLEMENT
  join ENTANGLEMENTS_GEAROWNER
  on (ENTANGLEMENTS_ENTANGLEMENT.GEAR_OWNER_INFO_ID = ENTANGLEMENTS_GEAROWNER.ID)
;

-- remove the old field
alter table "ENTANGLEMENTS_GEAROWNER"
drop column "MISSING_GEAR"
;

