-- add nmfs_id column to entanglements_entanglement
/* note that the DEFAULT clause isn't generated by Django's table def, but makes
 * sense.
 */
alter table "entanglements_entanglement"
add "nmfs_id" varchar(255) NOT NULL DEFAULT ""
;

-- copy data form old column to new column
update entanglements_entanglement
set nmfs_id = (
  select nmfs_id
  from incidents_case
  where entanglements_entanglement.case_ptr_id = incidents_case.documentable_ptr_id
)
;

-- TODO check is the following returns anything:
select * from incidents_case where case_type != 'Entanglement' and nmfs_id != '';

-- remove nmfs_id column from incidents_case
/* can't drop columns in sqlite */